function directories = loadDir()

directories = {fullfile('Data','Test','Ade'),...
    fullfile('Data','Test', 'Alvin'),...
    fullfile('Data','Test', 'Ardy'),...
    fullfile('Data','Test', 'Daffa'),...
    fullfile('Data','Test', 'Dio'),...
    fullfile('Data','Test', 'Fadil'),...
    fullfile('Data','Test', 'Hanif'),...
    fullfile('Data','Test', 'Liu'),...
    fullfile('Data','Test', 'Maula'),...
    fullfile('Data','Test', 'Mentari'),...
    fullfile('Data','Test', 'Muadz'),...
    fullfile('Data','Test', 'Nada'),...
    fullfile('Data','Test', 'Redy'),...
    fullfile('Data','Test', 'Rezky'),...
    fullfile('Data','Test', 'Ria'),...
    fullfile('Data','Test', 'Sena'),...
    fullfile('Data','Test', 'Suryo'),...
    fullfile('Data','Test', 'Wiranata'),...
    fullfile('Data','Test', 'Yuda')...
    fullfile('Data','Test', 'Yusuf')};
end