function directories = loadDir()

directories = {fullfile('Data','Train','Ade'),...
    fullfile('Data','Train', 'Alvin'),...
    fullfile('Data','Train', 'Ardy'),...
    fullfile('Data','Train', 'Daffa'),...
    fullfile('Data','Train', 'Dio'),...
    fullfile('Data','Train', 'Fadil'),...
    fullfile('Data','Train', 'Hanif'),...
    fullfile('Data','Train', 'Liu'),...
    fullfile('Data','Train', 'Maula'),...
    fullfile('Data','Train', 'Mentari'),...
    fullfile('Data','Train', 'Muadz'),...
    fullfile('Data','Train', 'Nada'),...
    fullfile('Data','Train', 'Redy'),...
    fullfile('Data','Train', 'Rezky'),...
    fullfile('Data','Train', 'Ria'),...
    fullfile('Data','Train', 'Sena'),...
    fullfile('Data','Train', 'Suryo'),...
    fullfile('Data','Train', 'Wiranata'),...
    fullfile('Data','Train', 'Yuda')...
    fullfile('Data','Train', 'Yusuf')};
end