function directories = loadDir()

directories = {fullfile('Data','Ade'),...
    fullfile('Data', 'Alvin'),...
    fullfile('Data', 'Ardy'),...
    fullfile('Data', 'Daffa'),...
    fullfile('Data', 'Fadil'),...
    fullfile('Data', 'Hanif'),...
    fullfile('Data', 'Liu'),...
    fullfile('Data', 'Maula'),...
    fullfile('Data', 'Mentari'),...
    fullfile('Data', 'Muadz'),...
    fullfile('Data', 'Nada'),...
    fullfile('Data', 'Redy'),...
    fullfile('Data', 'Rezky'),...
    fullfile('Data', 'Ria'),...
    fullfile('Data', 'Sena'),...
    fullfile('Data', 'Wiranata'),...
    fullfile('Data', 'Yuda')...
    fullfile('Data', 'Yusuf')};
end