clear;
clc;
close all;

blockSize = 4;
patchSize = 16;
% directories = {' mac' , 'win'};
directories = {fullfile('Data','Ade'),...
    fullfile('Data', 'Alvin'),...
    fullfile('Data', 'Ardy'),...
    fullfile('Data', 'Daffa'),...
    fullfile('Data', 'Fadil'),...
    fullfile('Data', 'Hanif'),...
    fullfile('Data', 'Liu'),...
    fullfile('Data', 'Maula'),...
    fullfile('Data', 'Mentari'),...
    fullfile('Data', 'Muadz'),...
    fullfile('Data', 'Nada'),...
    fullfile('Data', 'Redy'),...
    fullfile('Data', 'Rezky'),...
    fullfile('Data', 'Ria'),...
    fullfile('Data', 'Sena'),...
    fullfile('Data', 'Wiranata'),...
    fullfile('Data', 'Yuda')...
    fullfile('Data', 'Yusuf')};
% directories = {dir('Data\**')}
% directories = {fullfile('Data','Ade'), fullfile('Data', 'Alvin')};

disp('Collecting features from dataset.. ')
features = CreateBagOfWords(blockSize, patchSize, directories, 0.8);

disp('Features collected, clustering.. ')
[codebook, assignments] = vl_kmeans(features', 80, 'Initialization', 'plusplus');

disp('Comparing dataset to codebook.. ')
[X Y] = CalcHistograms(codebook', blockSize, patchSize, directories, 1, 0.8);

% Save model
% extracted_feature = [X Y];
% save('extracted_features.mat', 'extracted_feature');

disp('Training SVM classifier.. ')
[W B] = vl_svmtrain(X, double(Y), 0.02);

disp('Success rate on train set: ')
sum(sign(W' * X + B) == Y) / length(Y)

[CROSS_VALID_SET CROSS_VALID_LABELS] = CalcHistograms(codebook', blockSize, patchSize, directories, 0, 0.8);
disp('Success rate on cross validation set: ')
sum(sign(W' * CROSS_VALID_SET + B) == CROSS_VALID_LABELS) / length(CROSS_VALID_LABELS)
